[package]
name = "product"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "*"
mongodb = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
futures-util = "*"
clap = { version = "*", features = ["derive"] }