[package]
name = "property"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "*"
mongodb = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
futures-util = "*"
chrono = "*"
rust_decimal = "*"
clap = { version = "*", features = ["derive"] }